theme: jekyll-theme-cayman

gems:
- jekyll-seo-tag

webmaster_verifications:
  google: ndedVztwbvmq-IfsOTWt-bB6zuRisEGroNJtM6-UIiA
  yandex: 1e6c039a8997cb35

google_site_verification: "ndedVztwbvmq-IfsOTWt-bB6zuRisEGroNJtM6-UIiA"
yandex_site_verification: "1e6c039a8997cb35"

title: JDY-08 Bluetooth
